# Generated by Django 4.1.5 on 2023-01-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('director', models.CharField(max_length=32)),
                ('main_actors', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=32)),
                ('year', models.CharField(max_length=16)),
                ('running_time', models.CharField(max_length=32)),
                ('rating', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
    ]
